/********************************************************************** 
       Dax measures
***********************************************************************/



//--------------------------------------------------------------------
//     TestMeasure
//-------------------------------------------------------------------- 

TestMeasure:=SUM(Table5[ColB])


//--------------------------------------------------------------------
//     TestMw
//-------------------------------------------------------------------- 

TestMw:=CALCULATE(
    SUM(Table5[ColB])
    )
    +100
    /1