EVALUATE(
			ADDCOLUMNS(
				ADDCOLUMNS(
					tbl_LatestInstance,
					"tbl_LatestInstance[INDEX]", 
					RANKX(ALL(tbl_LatestInstance),   tbl_LatestInstance[Code] & tbl_LatestInstance[Date] & tbl_LatestInstance[Description])
					),
				"MaxIndexForCode", MAXX(
						ALL(tbl_LatestInstance),
						tbl_LatestInstance[Index]
						)
				)
			)
			