EVALUATE

FILTER(
	tbl_LatestInstance,
	RANKX(
					FILTER(
							tbl_LatestInstance,
							tbl_LatestInstance[Code] = EARLIER(tbl_LatestInstance[Code])
							),
			tbl_LatestInstance[Date] & tbl_LatestInstance[Description]
		) = 1
	)